# Generated by Django 4.2.4 on 2023-09-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=10)),
                ('document_size', models.PositiveSmallIntegerField()),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
